version: '3.9'
services:
  app:
    # user: vscode
    
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/workspace:cached
      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
